### ISSUE TITLE
accidentally mixing two runtimes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#47]
* Character: could be any, let's run with [Barbara](https://rust-lang.github.io/wg-async-foundations/vision/characters/barbara.html)
* Brief summary: Barbara is using library X, which is based on async-std, then adds library Y, which is based on tokio. She has problems until she learns about how to start the tokio runtime correctly.
* Key points or morals (if known):
    * It is possible to have two runtimes working at once, but things don't always work by default, and it's not always easy to understand what's going on.
* Sources:
    * I've personally heard this story from several experienced async Rust devs.

**Comment by nikomatsakis** [comment]
Some elements of this blog post feel related:

https://kevinhoffman.medium.com/rust-async-and-the-terrible-horrible-no-good-very-bad-day-348ebc836274

> Lesson II — It is possible for a single dependency of your crate to be so tightly coupled to a future polling runtime that it effectively makes that runtime mandatory for all consumers.

**Comment by erickt** [comment]
To add on to this - sometimes it's impossible to use these libraries. For example, on Fuchsia we haven't implemented support for tokio, async-std, and etc. We'd love to someday support them, but we haven't stabilized a lot of the interfaces executors need, so we'd end up needing to impose a lot of upstream churn.

So instead, we've been trying to leverage "executor-less" flags (like https://github.com/hyperium/hyper, where we plug into it with https://cs.opensource.google/fuchsia/fuchsia/+/master:src/lib/fuchsia-hyper/). This works for us, but it can also be difficult for upstream projects to be pluggable like this. So for hyper, we ended up having to reimplement a lot of https://github.com/hyperium/hyper/tree/master/src/client because they didn't have a mechanism for abstract dns resolution.

**Comment by nikomatsakis** [comment]
@erickt it'd be really nice to turn that into more of a user story format, I think. I'm particularly interested to hear more about the lack of mechanism around abstract DNS resolution or other such things that you've hit. It sounds like you are saying that, to truly integrate, you would want higher-level integration hooks?
