### ISSUE TITLE
dropping database handles is hard

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#59]
* Brief summary: Barbara tried to use sqlx in [YouBuy], but she has problems around cancellation. Ultimately it comes down to the fact that, in `Drop`, the cleanup code to close the database handle is running in a spawned task, and there is a race condition between that task executing and other connections opening.
* Character: [Barbara], could kind of be anyone
* Key points or morals (if known):
    * @galich told me this story

[cast]: https://rust-lang.github.io/wg-async-foundations/vision/characters.html
[Barbara]: https://rust-lang.github.io/wg-async-foundations/vision/characters/barbara.html
[YouBuy]: https://rust-lang.github.io/wg-async-foundations/vision/projects/YouBuy.html

**Comment by galich** [comment]
A real life example: an app is using SQLite and runs a number of separate async tasks, some of them needs to write to the database. SQLite is a single user database that locks database when write is being done. Tasks seems to coordinate well with each other, but sometimes some random task fails to open database because "another process opened it".

After some fun investigation we nailed it to the sqlx crate dropping connection by spawning another async task. We expected connection and associated resources to be free after drop, but in reality it was freed with some lag. Sometimes it could interfere with the rest of the system.

**Comment by nikomatsakis** [comment]
cc @pcwalton and @nagisa -- re: async drop

**Comment by nikomatsakis** [comment]
Part of this blog post feels (maybe) related:

https://kevinhoffman.medium.com/rust-async-and-the-terrible-horrible-no-good-very-bad-day-348ebc836274

>     Lesson III — If you drop (or allow to be dropped) the tokio runtime, any pending tasks are cancelled.

**Comment by nagisa** [comment]
s/database// in general. Here's another very similar instance I recently have seen:

Barbara is implementing SLOW over a cloud messaging service. On the receiving side the messages are accompanied with a handle that allows code to acknowledge or not-acknowledge the message, as well as extend the timeout after which the message would automatically be considered to not-acknowledged. Barbara would like the library to enforce that the messages are always ACKd or NACKd, by sending a NACK when user does not say otherwise. Today Barbara is forced to rely on `#[must_use]` and users not setting timeouts too far into the future to emulate the desired behaviour.

Moral: story around resource cleanup is not quite complete in async Rust;
Source: Efforts to add a Subscriber API to the [hedwig](https://github.com/standard-ai/hedwig-rust) library;
Why Barbara: Sadly, one needs some serious preservance and confidence in their ability to wrestle Rust in order to succeed in writing any nontrivial async code today :(

**Comment by nikomatsakis** [comment]
@nagisa thanks! that's a great story. Maybe we can find someone to turn it into a PR...

**Comment by nikomatsakis** [comment]
We spent some time in the first call today working on a storified version of this. Here is the hackmd with some bullets and things](https://hackmd.io/wlGFXswdTkaguaxwatmNXQ?view#dropping-database-handles-is-hard-59)

@doc-jones was going to take a look at making a story out of this. =)

@rustbot assign @doc-jones

**Comment by nikomatsakis** [comment]
Oh dang.

**Comment by nikomatsakis** [comment]
@rustbot assign @doc-jones

Does this work now? :)
